"""AST-level check: helpers and gates must not contain task-specific entity names.

We scan code-level string literals (excluding docstrings) for words that appear
in `_task_corpus.txt` with very low frequency, and treat any such word that
is also non-generic (mixed-case or unusually long lowercase) as a violation.

Generic structural words ("source", "content", "length", "result", ...) are
allowed because they refer to event/field/route names, not task entities.
"""
from __future__ import annotations

import ast
import re
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[3]
CORPUS = ROOT / "harness" / "gaia" / "_task_corpus.txt"

# Files generated by the harness-grow skill that must not leak task entities.
TARGET_FILES = [
    ROOT / "harness" / "gaia" / "audit_gates.py",
    ROOT / "agent" / "v1" / "reducers" / "normalize.py",
    ROOT / "agent" / "v1" / "reducers" / "extract.py",
    ROOT / "agent" / "v1" / "reducers" / "route.py",
    ROOT / "agent" / "v1" / "llm_nodes" / "answer_direct.py",
    ROOT / "agent" / "v1" / "workflow.py",
    ROOT / "agent" / "v1" / "state.py",
    ROOT / "agent" / "v11" / "reducers" / "normalize_v11.py",
    ROOT / "agent" / "v11" / "reducers" / "route_v11.py",
    ROOT / "agent" / "v12" / "reducers" / "query_rewrite.py",
    ROOT / "agent" / "v14" / "llm_nodes" / "plan_retrieval_v14.py",
    ROOT / "agent" / "v14" / "llm_nodes" / "answer_direct_v14.py",
    ROOT / "agent" / "v14" / "tools" / "vision_v14.py",
    ROOT / "agent" / "v14" / "workflow.py",
]

# Generic structural / programming words that may legitimately appear.
GENERIC_ALLOWLIST = {
    "answer", "answers", "result", "final", "content", "length", "stop",
    "source", "opened", "started", "ended", "system", "user", "model",
    "task", "tasks", "stage", "stages", "extras", "fields", "event", "events",
    "node", "nodes", "route", "routed", "block", "blocked", "submit",
    "needs", "file", "retrieval", "direct", "parsed", "answered", "normalized",
    "prompt", "prompts", "question", "questions", "reason", "reasons", "error",
    "errors", "agent", "single", "short", "string", "number", "list", "lists",
    "comma", "separated", "output", "expected", "internally", "visible",
    "prefix", "trailing", "punctuation", "explanation", "step", "steps",
    "benchmark", "solving", "assistant", "think", "still", "present",
    "according", "stated", "listed", "published", "reported", "article",
    "paper", "study", "video", "recording", "episode", "report", "website",
    "page", "url", "https", "http",
    # v6+: tool / claim / source structural names
    "tool", "tools", "called", "returned", "claim", "claims", "extracted",
    "verified", "wikipedia", "search", "fetch", "query", "args", "drift",
    "argument", "arguments", "unsourced", "unverified", "evidence",
    "confidence", "quote", "title", "kind", "snippet", "hits", "limit",
    "redirect", "redirects", "minor", "wiki", "rest",
    # v11+: source-family structural keywords (describe SHAPES of references,
    # not specific task entities). Each names a class of authoritative source
    # the router uses to decide retrieval routing.
    "wikimedia", "wiktionary", "wikidata", "arxiv", "biorxiv", "medrxiv",
    "preprint", "youtube", "wayback", "archive", "libretext", "tropicos",
    "scikit", "learn", "usgs", "nasa", "ipcc", "merriam", "webster",
    "rotten", "tomatoes", "metacritic", "christgau",
    # cipher / encoding structural keywords (describe the prompt SHAPE)
    "caesar", "vigenere", "substitution", "atbash", "rot13", "cipher",
    "encrypted", "decode",
    # restaurant / menu / time-anchor SHAPE keywords
    "restaurant", "menu", "dinner", "lunch", "breakfast", "brunch", "cafe",
    "cafeteria",
    # English month names (structural date anchors, not entities)
    "january", "february", "march", "april", "june", "july", "august",
    "september", "october", "november", "december",
    # episode / season / series identifier keywords
    "season", "episode", "series", "instructions", "instruction",
    # hedge phrasings normalize_v11 strips deterministically
    "approximately", "approx", "about", "roughly", "around", "nearly", "some",
    # v12+: generic English question-word fragments used by query rewriter
    "long", "writer", "album", "song", "since", "year", "date", "color",
    "name", "word", "book", "movie", "between", "from", "since",
    # v14: generic vision-prompt vocabulary (no task entities)
    "describe", "image", "looking", "attached", "factually", "visible",
    "numbers", "colors", "labels", "shapes", "invent", "details", "unclear",
    "something", "exactly", "path",
    # v14: structural workflow keywords inherited from v13
    "unknown", "failed", "vision",
    # v14: provider-error structural fragments (not task entities)
    "unable", "access", "non", "serverless", "capability",
    "unavailable", "gap",
}


def _is_docstring_constant(node: ast.Constant, docstrings: set[int]) -> bool:
    return id(node) in docstrings


def _collect_docstrings(tree: ast.AST) -> set[int]:
    out: set[int] = set()
    for parent in ast.walk(tree):
        body = getattr(parent, "body", None)
        if isinstance(body, list) and body:
            first = body[0]
            if (
                isinstance(first, ast.Expr)
                and isinstance(first.value, ast.Constant)
                and isinstance(first.value.value, str)
            ):
                out.add(id(first.value))
    return out


def _corpus_freq() -> dict[str, int]:
    text = CORPUS.read_text().lower()
    toks = re.findall(r"[a-z][a-z0-9_]+", text)
    out: dict[str, int] = {}
    for t in toks:
        out[t] = out.get(t, 0) + 1
    return out


@pytest.mark.parametrize("path", TARGET_FILES, ids=lambda p: p.name)
def test_no_task_entity_literals(path: Path) -> None:
    """Reject any code literal containing a rare corpus word that is not generic."""
    assert path.exists(), f"missing target: {path}"
    src = path.read_text()
    tree = ast.parse(src)
    docstrings = _collect_docstrings(tree)
    freq = _corpus_freq()

    violations: list[tuple[str, int, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Constant) or not isinstance(node.value, str):
            continue
        if _is_docstring_constant(node, docstrings):
            continue
        for word in re.findall(r"[A-Za-z][A-Za-z0-9_]*", node.value):
            wl = word.lower()
            if len(wl) < 4:
                continue
            if wl in GENERIC_ALLOWLIST:
                continue
            f = freq.get(wl, 0)
            # Only flag tokens that appear in the corpus (so we know they could
            # be task-specific) AND with low frequency (<= 2 means task-specific).
            if 0 < f <= 2:
                violations.append((word, f, node.value[:60]))

    assert not violations, (
        f"task-specific literals leaked into {path.name}: {violations}"
    )
